# Generated by Django 2.1.3 on 2019-01-13 04:28

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('chinese_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文名字')),
                ('img_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='头像路径')),
                ('desc', models.TextField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atc_topic', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('atc_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('atc_content', models.TextField(max_length=2000, null=True, verbose_name='内容')),
                ('click_count', models.IntegerField(default=0, null=True, verbose_name='点击次数')),
                ('like_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞次数')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 13, 12, 28, 28, 453197), null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2019, 1, 13, 12, 28, 28, 453197), null=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章表',
                'db_table': 'tbl_article',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cg_name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('cg_desc', models.TextField(blank=True, max_length=1000, null=True, verbose_name='分类描述')),
                ('imgpath', models.CharField(blank=True, max_length=500, null=True)),
                ('articles', models.ManyToManyField(blank=True, to='blog.Article')),
            ],
            options={
                'verbose_name': '文章分类',
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cmt_content', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 1, 13, 12, 28, 28, 454163), null=True)),
                ('like_count', models.IntegerField(default=0, null=True)),
                ('super_comment', models.IntegerField(blank=True, default=None, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('atc_id', models.ForeignKey(on_delete=False, to='blog.Article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论表',
                'db_table': 'tbl_comment',
            },
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remote_addr', models.CharField(max_length=100, null=True)),
                ('http_user_agent', models.CharField(max_length=200, null=True)),
                ('http_referer', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': '用户跟踪表',
                'db_table': 'tbl_user_track',
            },
        ),
    ]
